### PR TITLE
Update strings.xml 803059

### PR DESCRIPTION
**Pull request by zeeeeeky**
This is the latest translation for Croatian (Hrvatski Jezik)

### CODE REVIEW

**Review by zeeeeeky — COMMENTED** [review]
Just ignore the obvious grammar mistakes that I'm leaving in English, had autocorrection turned on for my own language

**Comment by zeeeeeky** [comment]
Check it out

**Comment by zeeeeeky** [comment]
@majaaaa1 Can you please check my translation

**Comment by Majaaaa1** [comment]
Da li si presao kroz ceo file?

**Comment by zeeeeeky** [comment]
> Da li si presao kroz ceo file? 

@Majaaaa1 Jesam, zasto pitas jesi li vidjela gresku negdje?

**Comment by Majaaaa1** [comment]
Da ali zelim da vidim gotov ceo file,onaj finalni pa da ti posaljem greske.

**Comment by zeeeeeky** [comment]
> Da ali zelim da vidim gotov ceo file,onaj finalni pa da ti posaljem greske.

Ok samo treba merge-at valjda

**Pull request merged**
